import React, { useState } from 'react';
import { X, Download, FileText, Leaf, Droplets, Zap, AlertTriangle, CheckCircle2, RefreshCw } from 'lucide-react';

const NUTRIENTS = [
  { name: 'Nitrogen (N)', key: 'n', value: 248, unit: 'kg/ha', optimal: [280, 420], color: '#22c55e' },
  { name: 'Phosphorus (P)', key: 'p', value: 18, unit: 'kg/ha', optimal: [20, 40], color: '#3b82f6' },
  { name: 'Potassium (K)', key: 'k', value: 196, unit: 'kg/ha', optimal: [150, 250], color: '#f59e0b' },
  { name: 'Sulphur (S)', key: 's', value: 9, unit: 'mg/kg', optimal: [10, 20], color: '#8b5cf6' },
  { name: 'Zinc (Zn)', key: 'zn', value: 0.62, unit: 'mg/kg', optimal: [0.6, 2.0], color: '#d97706' },
];

const PARAMETERS = [
  { label: 'pH Level', value: 6.8, normal: '6.5–7.5', status: 'good', unit: '' },
  { label: 'Organic Carbon', value: 0.52, normal: '>0.75%', status: 'low', unit: '%' },
  { label: 'EC (Salinity)', value: 0.38, normal: '<0.80', status: 'good', unit: 'dS/m' },
  { label: 'Moisture', value: 38, normal: '40–60%', status: 'low', unit: '%' },
];

const statusColor = { good: '#22c55e', low: '#f59e0b', high: '#ef4444' };
const statusLabel = { good: '✓ Optimal', low: '↑ Low', high: '↓ High' };

const SoilReportModal = ({ onClose }) => {
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [activeSection, setActiveSection] = useState('nutrients');

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setGenerated(true);
    }, 2000);
  };

  const handleDownload = () => {
    // In production: generate real PDF via jsPDF or server
    const content = `
AGRIBRIDGE SOIL HEALTH CARD
============================
Farmer: Ramesh Kumar
Date: ${new Date().toLocaleDateString('en-IN')}
State: Uttar Pradesh | District: Varanasi
Land: 2.5 acres | Soil: Loamy
Survey No: UP-VNS-2024-7291
----------------------------
NUTRIENT STATUS
N (Nitrogen): 248 kg/ha — LOW (need 280-420)
P (Phosphorus): 18 kg/ha — LOW (need 20-40)
K (Potassium): 196 kg/ha — OPTIMAL
S (Sulphur): 9 mg/kg — LOW
Zn (Zinc): 0.62 mg/kg — OPTIMAL
----------------------------
SOIL PARAMETERS
pH: 6.8 — Optimal
Organic Carbon: 0.52% — Low
EC: 0.38 dS/m — Optimal
Moisture: 38% — Low
----------------------------
RECOMMENDATIONS
1. Apply Urea 50 kg/acre for Nitrogen deficit
2. Apply SSP 20 kg/acre for Phosphorus
3. Apply Ammonium Sulphate for Sulphur
4. Add FYM 4 tonnes/acre to improve Organic Carbon
5. Irrigate to bring moisture to 45%
----------------------------
Generated by AgriBridge AI
https://agribridge.app
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'SoilHealthCard_AgriBridge.txt';
    a.click(); URL.revokeObjectURL(url);
  };

  return (
    <div className="modal-backdrop">
      <div className="modal-box" style={{ maxWidth: 560 }}>
        <div style={{ background: 'linear-gradient(135deg, #78350f 0%, #92400e 100%)', padding: '24px 28px', color: 'white' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div style={{ display: 'flex', gap: 14, alignItems: 'center' }}>
              <div style={{ background: 'rgba(255,255,255,0.2)', padding: 10, borderRadius: 14 }}><FileText size={24} /></div>
              <div>
                <div style={{ fontSize: 10, letterSpacing: '2px', opacity: 0.65, fontWeight: 600, textTransform: 'uppercase' }}>Govt-format · Shareable</div>
                <h2 style={{ fontFamily: "'Syne',system-ui", fontSize: 22, fontWeight: 800, margin: 0 }}>Soil Health Report</h2>
              </div>
            </div>
            <button onClick={onClose} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', color: 'white', padding: 8, borderRadius: 10, cursor: 'pointer', display: 'flex' }}><X size={20} /></button>
          </div>
          {/* Farmer strip */}
          <div style={{ marginTop: 16, background: 'rgba(255,255,255,0.1)', borderRadius: 14, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', border: '1px solid rgba(255,255,255,0.1)' }}>
            <div>
              <div style={{ fontSize: 13, fontWeight: 700 }}>Ramesh Kumar · 2.5 acres</div>
              <div style={{ fontSize: 11, opacity: 0.65, marginTop: 2 }}>Varanasi, U.P. · Loamy Soil · Sampled: {new Date().toLocaleDateString('en-IN')}</div>
            </div>
            <div style={{ background: '#22c55e', padding: '4px 12px', borderRadius: 20, fontSize: 11, fontWeight: 700 }}>ID: UP-7291</div>
          </div>
        </div>

        <div style={{ padding: '20px 28px 28px', maxHeight: '65vh', overflowY: 'auto' }}>
          {/* Section tabs */}
          <div style={{ display: 'flex', background: '#f5f5f5', padding: 4, borderRadius: 14, marginBottom: 20 }}>
            {[['nutrients', '🌱 Nutrients'], ['params', '🔬 Parameters'], ['reco', '📋 Action Plan']].map(([v, l]) => (
              <button key={v} onClick={() => setActiveSection(v)} style={{ flex: 1, padding: '7px', borderRadius: 11, border: 'none', cursor: 'pointer', fontWeight: 700, fontSize: 12, fontFamily: 'inherit', transition: 'all 0.2s', background: activeSection === v ? 'white' : 'transparent', color: activeSection === v ? '#78350f' : '#888', boxShadow: activeSection === v ? '0 2px 8px rgba(0,0,0,0.08)' : 'none' }}>{l}</button>
            ))}
          </div>

          {/* NUTRIENTS */}
          {activeSection === 'nutrients' && (
            <div style={{ animation: 'fadeUp 0.4s ease', display: 'flex', flexDirection: 'column', gap: 14 }}>
              {NUTRIENTS.map((n, i) => {
                const pct = Math.min(100, (n.value / n.optimal[1]) * 100);
                const isLow = n.value < n.optimal[0];
                const isHigh = n.value > n.optimal[1];
                const status = isLow ? 'low' : isHigh ? 'high' : 'good';
                return (
                  <div key={i} style={{ background: '#fafafa', border: '1px solid #f0f0f0', borderRadius: 18, padding: '16px 20px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                      <div style={{ fontWeight: 700, fontSize: 14, color: '#1a1a1a' }}>{n.name}</div>
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                        <span style={{ fontFamily: "'Syne',system-ui", fontWeight: 800, fontSize: 18, color: n.color }}>{n.value}</span>
                        <span style={{ fontSize: 11, color: '#aaa' }}>{n.unit}</span>
                        <span style={{ background: `${statusColor[status]}15`, color: statusColor[status], border: `1px solid ${statusColor[status]}30`, fontSize: 11, fontWeight: 700, padding: '3px 8px', borderRadius: 20 }}>{statusLabel[status]}</span>
                      </div>
                    </div>
                    <div style={{ height: 8, background: '#e5e7eb', borderRadius: 4, overflow: 'hidden', position: 'relative' }}>
                      {/* Optimal range band */}
                      <div style={{ position: 'absolute', left: `${(n.optimal[0] / n.optimal[1]) * 90}%`, width: '20%', height: '100%', background: 'rgba(34,197,94,0.15)', borderRadius: 2 }} />
                      <div style={{ height: '100%', background: n.color, borderRadius: 4, width: `${pct}%`, transition: 'width 0.6s ease' }} />
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 5 }}>
                      <span style={{ fontSize: 10, color: '#aaa' }}>0</span>
                      <span style={{ fontSize: 10, color: '#22c55e', fontWeight: 600 }}>Optimal: {n.optimal[0]}–{n.optimal[1]}</span>
                      <span style={{ fontSize: 10, color: '#aaa' }}>{n.optimal[1]}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {/* PARAMETERS */}
          {activeSection === 'params' && (
            <div style={{ animation: 'fadeUp 0.4s ease', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
              {PARAMETERS.map((p, i) => (
                <div key={i} style={{ background: `${statusColor[p.status]}08`, border: `1px solid ${statusColor[p.status]}25`, borderRadius: 18, padding: '18px 18px' }}>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#aaa', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: 6 }}>{p.label}</div>
                  <div style={{ fontFamily: "'Syne',system-ui", fontSize: 28, fontWeight: 800, color: statusColor[p.status] }}>{p.value}{p.unit}</div>
                  <div style={{ fontSize: 11, color: '#888', marginTop: 4 }}>Normal: {p.normal}</div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 8 }}>
                    {p.status === 'good' ? <CheckCircle2 size={14} color={statusColor[p.status]} /> : <AlertTriangle size={14} color={statusColor[p.status]} />}
                    <span style={{ fontSize: 11, fontWeight: 700, color: statusColor[p.status] }}>{statusLabel[p.status]}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* ACTION PLAN */}
          {activeSection === 'reco' && (
            <div style={{ animation: 'fadeUp 0.4s ease' }}>
              {[
                { priority: 'high', label: 'Apply Urea 50 kg/acre', detail: 'Nitrogen is 13% below optimal. Apply top dressing before next irrigation.', icon: '🌿' },
                { priority: 'high', label: 'Apply SSP 20 kg/acre', detail: 'Phosphorus deficient. SSP improves root development and early growth.', icon: '🪨' },
                { priority: 'medium', label: 'Add FYM 4 tonnes/acre', detail: 'Organic Carbon at 0.52% — low. FYM improves soil structure and retention.', icon: '🌱' },
                { priority: 'medium', label: 'Apply Ammonium Sulphate', detail: 'Sulphur at 9 mg/kg — slightly below optimal. Improves protein synthesis in wheat.', icon: '⚗️' },
                { priority: 'low', label: 'Irrigate to 45% moisture', detail: 'Current moisture 38% — below optimal. Schedule 1 irrigation within 3 days.', icon: '💧' },
              ].map((r, i) => (
                <div key={i} style={{ display: 'flex', gap: 12, padding: '14px 16px', background: r.priority === 'high' ? '#fef2f2' : r.priority === 'medium' ? '#fefce8' : '#f0fdf4', border: `1px solid ${r.priority === 'high' ? 'rgba(239,68,68,0.15)' : r.priority === 'medium' ? 'rgba(245,158,11,0.15)' : 'rgba(34,197,94,0.15)'}`, borderRadius: 16, marginBottom: 10 }}>
                  <div style={{ fontSize: 22, flexShrink: 0 }}>{r.icon}</div>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: 14, color: '#1a1a1a', marginBottom: 3 }}>{r.label}</div>
                    <div style={{ fontSize: 12, color: '#666', lineHeight: 1.5 }}>{r.detail}</div>
                  </div>
                  <div style={{ marginLeft: 'auto', flexShrink: 0 }}>
                    <span style={{ fontSize: 9, fontWeight: 800, padding: '3px 8px', borderRadius: 20, textTransform: 'uppercase', letterSpacing: '1px', background: r.priority === 'high' ? '#fee2e2' : r.priority === 'medium' ? '#fef3c7' : '#dcfce7', color: r.priority === 'high' ? '#b91c1c' : r.priority === 'medium' ? '#92400e' : '#166534' }}>{r.priority}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Generate / Download buttons */}
          <div style={{ marginTop: 20, display: 'flex', gap: 10 }}>
            {!generated ? (
              <button onClick={handleGenerate} disabled={generating} style={{ flex: 1, padding: '14px', background: generating ? '#e5e7eb' : 'linear-gradient(135deg,#78350f,#92400e)', color: generating ? '#aaa' : 'white', border: 'none', borderRadius: 16, fontWeight: 700, fontSize: 14, cursor: generating ? 'not-allowed' : 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: generating ? 'none' : '0 8px 24px rgba(120,53,15,0.3)' }}>
                {generating ? <><RefreshCw size={16} style={{ animation: 'spinSlow 1s linear infinite' }} /> Generating PDF...</> : <><FileText size={16} /> Generate PDF Report</>}
              </button>
            ) : (
              <>
                <button onClick={handleDownload} style={{ flex: 1, padding: '14px', background: 'linear-gradient(135deg,#166534,#15803d)', color: 'white', border: 'none', borderRadius: 16, fontWeight: 700, fontSize: 14, cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, boxShadow: '0 8px 24px rgba(22,101,52,0.3)' }}>
                  <Download size={16} /> Download Report
                </button>
                <button onClick={() => { setGenerated(false); }} style={{ padding: '14px 16px', background: '#f5f5f5', border: '1px solid #e5e7eb', borderRadius: 16, cursor: 'pointer', display: 'flex', alignItems: 'center', color: '#888' }}>
                  <RefreshCw size={16} />
                </button>
              </>
            )}
          </div>
          {generated && (
            <p style={{ textAlign: 'center', fontSize: 11, color: '#aaa', marginTop: 8 }}>
              Share this report with your bank, KVK, or insurance provider
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

export default SoilReportModal;
